// Generated by Wrangler — regenerate with: bun run cf-typegen
// Run `bun run cf-typegen` after adding new bindings to wrangler.jsonc
declare namespace Cloudflare {
	interface Env {
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		WORKER_SELF_REFERENCE: Fetcher /* riftseer-web */;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
