/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv ./cloudflare-env.d.ts --include-runtime false` (hash: d703b3460a17d015c6c97f56cccea15a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env {
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		NEXT_PUBLIC_API_URL: "https://api.riftseer.com";
		NEXT_PUBLIC_APP_URL: "https://riftseer.com";
		C15T_DATABASE_URL: string;
		WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_API_URL" | "NEXT_PUBLIC_APP_URL" | "C15T_DATABASE_URL">> {}
}
