"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Upload } from "lucide-react";
import type { Oracle, Printing } from "@riftseer/types";
import { printingImageUrl } from "@riftseer/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { suggestAltTextForCard } from "@/features/admin/alt-text";
import { usePrintingMutations } from "@/features/admin/hooks/use-admin-mutations";
import { AdminSection } from "./admin-form-field";

const ACCEPTED_TYPES = ["image/jpeg", "image/png", "image/webp", "image/avif", "image/gif"];

export function AdminCardImagePanel({ oracle, printing }: { oracle: Oracle; printing: Printing }) {
  const router = useRouter();
  const inputRef = React.useRef<HTMLInputElement>(null);
  const [file, setFile] = React.useState<File | null>(null);
  const suggestedAlt = suggestAltTextForCard(oracle, printing);
  const [altText, setAltText] = React.useState(printing.image_alt_text ?? suggestedAlt);
  const { uploadImage } = usePrintingMutations();
  const preview = React.useMemo(() => file ? URL.createObjectURL(file) : printingImageUrl(printing, "normal"), [file, printing]);
  React.useEffect(() => () => { if (file && preview) URL.revokeObjectURL(preview); }, [file, preview]);

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    if (!file) return;
    const formData = new FormData();
    formData.append("file", file);
    if (altText.trim()) formData.append("accessibility_text", altText.trim());
    try {
      await uploadImage.mutateAsync([printing.id, formData]);
      setFile(null);
      if (inputRef.current) inputRef.current.value = "";
      router.refresh();
    } catch {}
  }

  return (
    <AdminSection heading="Card art" description="Uploads replace this printing's art and lock it against ingest. WebP variants are generated by the image queue.">
      <form onSubmit={(event) => void submit(event)} className="flex flex-wrap items-start gap-6">
        {preview ? <img src={preview} alt={altText || oracle.name} className="w-32 rounded-md border" /> : <div className="text-muted-foreground flex h-44 w-32 items-center justify-center rounded-md border text-xs">No hosted art</div>}
        <div className="flex min-w-60 flex-1 flex-col gap-4">
          <div><Label htmlFor="card-image-file">Replacement image</Label><Input id="card-image-file" ref={inputRef} type="file" accept={ACCEPTED_TYPES.join(",")} onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><p className="text-muted-foreground mt-1 text-xs">JPEG, PNG, WebP, AVIF, or GIF up to 20 MB.</p></div>
          <div><Label htmlFor="card-image-alt">Alt text</Label><Input id="card-image-alt" value={altText} onChange={(event) => setAltText(event.target.value)} maxLength={2000} placeholder={suggestedAlt} />{suggestedAlt !== altText ? <button type="button" className="text-muted-foreground mt-1 text-xs underline-offset-4 hover:underline" onClick={() => setAltText(suggestedAlt)}>Use suggested alt text</button> : null}</div>
          <Button type="submit" disabled={!file || uploadImage.isPending}><Upload />{uploadImage.isPending ? "Uploading…" : "Upload image"}</Button>
        </div>
      </form>
    </AdminSection>
  );
}
