"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Upload } from "lucide-react";
import { toast } from "sonner";
import type { Card } from "@riftseer/types";
import { cardImageUrl } from "@riftseer/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useCardMutations } from "@/features/admin/hooks/use-admin-mutations";
import { AdminSection } from "./admin-form-field";

/** Mirrors the API's accepted types and 20 MB ceiling so bad files fail locally. */
const ACCEPTED_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/avif",
  "image/gif",
];
const MAX_BYTES = 20 * 1024 * 1024;

export function AdminCardImagePanel({ card }: { card: Card }) {
  const router = useRouter();
  const inputRef = React.useRef<HTMLInputElement>(null);
  const [file, setFile] = React.useState<File | null>(null);
  const storedAlt = card.media?.accessibility_text ?? "";
  const [altText, setAltText] = React.useState(storedAlt);

  // `useState` only seeds on mount, and the editor renders this panel without a
  // key, so navigating between cards or refreshing after a save would leave the
  // previous card's alt text in the input. Resync only when the stored value
  // actually changes, so unrelated re-renders keep an in-progress edit.
  const syncKey = `${card.id}:${storedAlt}`;
  const syncedTo = React.useRef(syncKey);
  React.useEffect(() => {
    if (syncedTo.current === syncKey) return;
    syncedTo.current = syncKey;
    setAltText(storedAlt);
  }, [syncKey, storedAlt]);

  const { uploadImage } = useCardMutations();

  const preview = cardImageUrl(card.media, "small");

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    if (!file) {
      toast.error("Choose an image first");
      return;
    }
    if (!ACCEPTED_TYPES.includes(file.type)) {
      toast.error("Use a JPEG, PNG, WebP, AVIF, or GIF image");
      return;
    }
    if (file.size === 0 || file.size > MAX_BYTES) {
      toast.error("Image must be between 1 byte and 20 MB");
      return;
    }

    const formData = new FormData();
    formData.append("file", file);
    const trimmedAlt = altText.trim();
    if (trimmedAlt) formData.append("accessibility_text", trimmedAlt);

    try {
      await uploadImage.mutateAsync([card.id, formData]);
    } catch {
      // Already surfaced as a toast — keep the chosen file so it can be retried.
      return;
    }
    setFile(null);
    if (inputRef.current) inputRef.current.value = "";
    // `card` is server-rendered: without this the preview and source_provider
    // keep showing the pre-upload art.
    router.refresh();
  }

  return (
    <AdminSection
      heading="Card art"
      description="Uploads replace the hosted art and mark the image as admin-sourced, so ingest will not overwrite it. WebP variants are generated by the image queue."
    >
      <form
        onSubmit={(event) => void submit(event)}
        className="flex flex-wrap items-start gap-6"
      >
        {preview ? (
          <img
            src={preview}
            alt={card.media?.accessibility_text ?? card.name}
            className="w-32 rounded-md border"
          />
        ) : (
          <div className="text-muted-foreground flex h-44 w-32 items-center justify-center rounded-md border text-center text-xs">
            No hosted art
          </div>
        )}

        <div className="flex min-w-60 flex-1 flex-col gap-4">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="card-image-file">Replacement image</Label>
            <Input
              id="card-image-file"
              ref={inputRef}
              type="file"
              accept={ACCEPTED_TYPES.join(",")}
              onChange={(e) => setFile(e.target.files?.[0] ?? null)}
            />
            <p className="text-muted-foreground text-xs">
              JPEG, PNG, WebP, AVIF, or GIF up to 20 MB.
            </p>
          </div>

          <div className="flex flex-col gap-1.5">
            <Label htmlFor="card-image-alt">Alt text</Label>
            <Input
              id="card-image-alt"
              value={altText}
              onChange={(e) => setAltText(e.target.value)}
              maxLength={2000}
              placeholder="Describe the art for screen readers"
            />
          </div>

          <div>
            <Button type="submit" disabled={!file || uploadImage.isPending}>
              <Upload aria-hidden="true" />
              {uploadImage.isPending ? "Uploading…" : "Upload image"}
            </Button>
          </div>

          {card.media?.source_provider && (
            <p className="text-muted-foreground text-xs">
              Current source: {card.media.source_provider}
            </p>
          )}
        </div>
      </form>
    </AdminSection>
  );
}
