/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=GeneratedEnv src/worker-configuration.d.ts` (hash: d7cec9b5c97998bd484f7a688b155bbb)
interface __BaseEnv_GeneratedEnv {
	CARD_IMAGES: R2Bucket;
	CARD_IMAGE_QUEUE: Queue;
	CARD_PROVIDER: "supabase";
	LEGAL_TERMS_VERSION: "2";
	LEGAL_PRIVACY_VERSION: "4";
	SITE_ORIGIN: "https://riftseer.com";
	ADMIN_USER_IDS: "";
	CARD_IMAGE_BASE_URL: "https://img.riftseer.com";
	METAFY_COMMUNITY_ID: "riftseer";
	METAFY_REDIRECT_URI: "https://riftseer.com/auth/metafy/callback";
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	SUPABASE_ANON_KEY: string;
	METAFY_CLIENT_SECRET: string;
	METAFY_CLIENT_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CARD_PROVIDER" | "LEGAL_TERMS_VERSION" | "LEGAL_PRIVACY_VERSION" | "SITE_ORIGIN" | "ADMIN_USER_IDS" | "CARD_IMAGE_BASE_URL" | "METAFY_COMMUNITY_ID" | "METAFY_REDIRECT_URI" | "SUPABASE_URL" | "SUPABASE_SERVICE_ROLE_KEY" | "SUPABASE_ANON_KEY" | "METAFY_CLIENT_SECRET" | "METAFY_CLIENT_ID">> {}
}
