/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=GeneratedEnv src/worker-configuration.d.ts` (hash: 97b000d49c7432921d7c11c96d4a778b)
interface __BaseEnv_GeneratedEnv {
	CARD_IMAGES: R2Bucket;
	CARD_IMAGE_QUEUE: Queue;
	IMAGES: ImagesBinding;
	RIFTCODEX_BASE_URL: "https://api.riftcodex.com";
	RIFTBOUND_GALLERY_BASE_URL: "https://content.publishing.riotgames.com";
	UPSTREAM_TIMEOUT_MS: "30000";
	CARD_IMAGE_BASE_URL: "https://img.riftseer.com";
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RIFTCODEX_BASE_URL" | "RIFTBOUND_GALLERY_BASE_URL" | "UPSTREAM_TIMEOUT_MS" | "CARD_IMAGE_BASE_URL" | "SUPABASE_URL" | "SUPABASE_SERVICE_ROLE_KEY">> {}
}
