import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for Supabase-specific docs under supabase/docs.
const sidebars: SidebarsConfig = {
  supabaseSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;

