import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Main dev docs sidebar. We autogenerate from the root of
  // packages/ingest-worker/docs (configured as the docs path).
  ingestWorkerSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
